### ISSUE TITLE
URL Update

### ISSUE THREAD

**Issue by tylerezimmerman** [DelineaXPM/dsv-k8s#36]
**Description of the issue**

Can this URL be updated (https://gist.github.com/amigus/b4e6e642f88e756be1996e44a1c35349) to use a different resource. 

**Steps to reproduce**

`ℹ️ All this assumes that the injector uses a certificate signed by the cluster CA.
There are several options like [cert-manager](https://cert-manager.io/)
for getting cluster-signed certs, however,
this simple [bash script](https://gist.github.com/amigus/b4e6e642f88e756be1996e44a1c35349)
will request and grant a suitable certificate from the cluster using cURL and OpenSSL.`

**Comment by sheldonhull** [comment]
This isn't executed in automation, but just a reference for a gist that provides a reference script. I'd leave this since @amigus might update with any fixes in the future and it's not core to the requirements or setup of the app we have. It's more administration for the cluster and I'd wager this script is unlikely to be used over other cert manager automation.

Let's leave it and can fork or internalize if it's ever needed, otherwise just a good reference for those charting their own path 😀 

@amigus if you want us to fork or do something else with that let us know, otherwise I'm just leaving it pointing to that script in case someone finds it useful.

**Comment by amigus** [comment]
Agreed.
